export const themeOrder = ['dark', 'gold', 'light'];

export const themes = {
  dark: {
    key: 'dark',
    label: 'Dark',
    colorScheme: 'light',
    colors: {
      textPrimary: '#1a1a1a',
      textSecondary: '#2d2d2d',
      textMuted: 'rgba(26, 26, 26, 0.65)',
      textInverse: '#ffffff',
      textInverseMuted: '#f8f9fa',
      icon: '#2d2d2d',
      backgroundPage: '#f8f9fa',
      backgroundSurface: '#ffffff',
      backgroundMuted: '#f8f9fa',
      backgroundContrast: '#2d2d2d',
      backgroundContrastMuted: '#1a1a1a',
      border: '#dfe3e8',
      borderStrong: '#cfd5db',
      accent: '#2d2d2d',
      accentStrong: '#1a1a1a',
      accentSoft: 'rgba(45, 45, 45, 0.12)',
      focus: '#2d2d2d',
      success: '#15803d',
      warning: '#b45309',
      danger: '#dc2626',
      info: '#1d4ed8',
      selected: '#2d2d2d',
      selectedBg: 'rgba(45, 45, 45, 0.08)'
    },
    typography: {
      body: 'Inter, sans-serif',
      heading: '"Cormorant Garamond", serif',
      accent: '"Lucy Said Ok Personal Use Italic", "Cormorant Garamond", serif'
    },
    components: {
      buttonPrimary: 'btn-primary theme-button-primary',
      buttonOutline: 'btn-outline theme-button-outline',
      link: 'theme-link',
      input: 'theme-input',
      navItem: 'theme-nav-item',
      surface: 'theme-bg-surface theme-border',
      surfaceMuted: 'theme-bg-muted theme-border'
    },
    utilities: {
      textPrimary: 'theme-text-primary',
      textSecondary: 'theme-text-secondary',
      textMuted: 'theme-text-muted',
      textInverse: 'theme-text-inverse',
      bgPage: 'theme-bg-page',
      bgSurface: 'theme-bg-surface',
      bgMuted: 'theme-bg-muted',
      bgContrast: 'theme-bg-contrast',
      border: 'theme-border',
      borderStrong: 'theme-border-strong',
      selected: 'theme-selected',
      selectedBg: 'theme-selected-bg',
      textDanger: 'text-red-600'
    },
    cssVars: {
      'font-body': 'Inter, sans-serif',
      'font-heading': '"Cormorant Garamond", serif',
      'font-accent': '"Lucy Said Ok Personal Use Italic", "Cormorant Garamond", serif',
      'color-text-primary': '#1a1a1a',
      'color-text-secondary': '#2d2d2d',
      'color-text-muted': 'rgba(26, 26, 26, 0.65)',
      'color-text-inverse': '#ffffff',
      'color-text-inverse-muted': '#f8f9fa',
      'color-icon': '#2d2d2d',
      'color-bg-page': '#f8f9fa',
      'color-bg-surface': '#ffffff',
      'color-bg-muted': '#f8f9fa',
      'color-bg-contrast': '#2d2d2d',
      'color-bg-contrast-muted': '#1a1a1a',
      'color-border': '#dfe3e8',
      'color-border-strong': '#cfd5db',
      'color-accent': '#2d2d2d',
      'color-accent-strong': '#1a1a1a',
      'color-accent-soft': 'rgba(45, 45, 45, 0.12)',
      'color-focus': '#2d2d2d',
      'color-success': '#15803d',
      'color-warning': '#b45309',
      'color-danger': '#dc2626',
      'color-info': '#1d4ed8',
      'color-success-bg': 'rgba(21, 128, 61, 0.12)',
      'color-warning-bg': 'rgba(180, 83, 9, 0.12)',
      'color-danger-bg': 'rgba(220, 38, 38, 0.12)',
      'color-info-bg': 'rgba(29, 78, 216, 0.12)',
      'color-selected': '#2d2d2d',
      'color-selected-bg': 'rgba(45, 45, 45, 0.08)',
      'color-button-bg': '#1a1a1a',
      'color-button-text': '#ffffff',
      'color-button-border': '#1a1a1a',
      'color-button-outline-text': '#1a1a1a',
      'color-button-outline-bg': 'transparent',
      'color-button-outline-border': '#1a1a1a',
      'color-input-bg': '#ffffff',
      'color-input-border': '#dfe3e8',
      'color-input-text': '#1a1a1a',
      'color-input-placeholder': 'rgba(26, 26, 26, 0.65)',
      'color-nav-bg': '#ffffff',
      'color-nav-border': '#dfe3e8',
      'color-logo-gold': '#c87c00',
      'color-logo-highlight': '#ffd65a',
      'color-logo-glow': 'rgba(198, 122, 0, 0.75)',
      'color-logo-glow-strong': 'rgba(255, 214, 90, 0.9)',
      'color-logo-glow-soft': 'rgba(198, 122, 0, 0.4)'
    }
  },
  light: {
    key: 'light',
    label: 'Light',
    colorScheme: 'dark',
    colors: {
      textPrimary: '#ffffff',
      textSecondary: '#f8f9fa',
      textMuted: 'rgba(248, 249, 250, 0.75)',
      textInverse: '#1a1a1a',
      textInverseMuted: '#2d2d2d',
      icon: '#f8f9fa',
      backgroundPage: '#1a1a1a',
      backgroundSurface: '#2d2d2d',
      backgroundMuted: '#1a1a1a',
      backgroundContrast: '#f8f9fa',
      backgroundContrastMuted: '#ffffff',
      border: '#3a3a3a',
      borderStrong: '#4a4a4a',
      accent: '#f8f9fa',
      accentStrong: '#ffffff',
      accentSoft: 'rgba(248, 249, 250, 0.12)',
      focus: '#f8f9fa',
      success: '#86efac',
      warning: '#fde68a',
      danger: '#fca5a5',
      info: '#93c5fd',
      selected: '#f8f9fa',
      selectedBg: 'rgba(248, 249, 250, 0.18)'
    },
    typography: {
      body: 'Inter, sans-serif',
      heading: '"Cormorant Garamond", serif',
      accent: '"Lucy Said Ok Personal Use Italic", "Cormorant Garamond", serif'
    },
    components: {
      buttonPrimary: 'btn-primary theme-button-primary',
      buttonOutline: 'btn-outline theme-button-outline',
      link: 'theme-link',
      input: 'theme-input',
      navItem: 'theme-nav-item',
      surface: 'theme-bg-surface theme-border',
      surfaceMuted: 'theme-bg-muted theme-border'
    },
    utilities: {
      textPrimary: 'theme-text-primary',
      textSecondary: 'theme-text-secondary',
      textMuted: 'theme-text-muted',
      textInverse: 'theme-text-inverse',
      bgPage: 'theme-bg-page',
      bgSurface: 'theme-bg-surface',
      bgMuted: 'theme-bg-muted',
      bgContrast: 'theme-bg-contrast',
      border: 'theme-border',
      borderStrong: 'theme-border-strong',
      selected: 'theme-selected',
      selectedBg: 'theme-selected-bg',
      textDanger: 'text-red-600'
    },
    cssVars: {
      'font-body': 'Inter, sans-serif',
      'font-heading': '"Cormorant Garamond", serif',
      'font-accent': '"Lucy Said Ok Personal Use Italic", "Cormorant Garamond", serif',
      'color-text-primary': '#ffffff',
      'color-text-secondary': '#f8f9fa',
      'color-text-muted': 'rgba(248, 249, 250, 0.75)',
      'color-text-inverse': '#1a1a1a',
      'color-text-inverse-muted': '#2d2d2d',
      'color-icon': '#f8f9fa',
      'color-bg-page': '#1a1a1a',
      'color-bg-surface': '#2d2d2d',
      'color-bg-muted': '#1a1a1a',
      'color-bg-contrast': '#f8f9fa',
      'color-bg-contrast-muted': '#ffffff',
      'color-border': '#3a3a3a',
      'color-border-strong': '#4a4a4a',
      'color-accent': '#f8f9fa',
      'color-accent-strong': '#ffffff',
      'color-accent-soft': 'rgba(248, 249, 250, 0.12)',
      'color-focus': '#f8f9fa',
      'color-success': '#86efac',
      'color-warning': '#fde68a',
      'color-danger': '#fca5a5',
      'color-info': '#93c5fd',
      'color-success-bg': 'rgba(134, 239, 172, 0.16)',
      'color-warning-bg': 'rgba(253, 230, 138, 0.16)',
      'color-danger-bg': 'rgba(252, 165, 165, 0.16)',
      'color-info-bg': 'rgba(147, 197, 253, 0.16)',
      'color-selected': '#f8f9fa',
      'color-selected-bg': 'rgba(248, 249, 250, 0.18)',
      'color-button-bg': '#ffffff',
      'color-button-text': '#1a1a1a',
      'color-button-border': '#ffffff',
      'color-button-outline-text': '#ffffff',
      'color-button-outline-bg': 'transparent',
      'color-button-outline-border': '#ffffff',
      'color-input-bg': '#2d2d2d',
      'color-input-border': '#4a4a4a',
      'color-input-text': '#ffffff',
      'color-input-placeholder': 'rgba(248, 249, 250, 0.7)',
      'color-nav-bg': '#1a1a1a',
      'color-nav-border': '#2d2d2d',
      'color-logo-gold': '#f9e076',
      'color-logo-highlight': '#f5e7a1',
      'color-logo-glow': 'rgba(249, 224, 118, 0.7)',
      'color-logo-glow-strong': 'rgba(245, 231, 161, 0.9)',
      'color-logo-glow-soft': 'rgba(249, 224, 118, 0.5)'
    }
  },
  gold: {
    key: 'gold',
    label: 'Gold',
    colorScheme: 'light',
    colors: {
      textPrimary: '#d4af37',
      textSecondary: '#ffd700',
      textMuted: 'rgba(212, 175, 55, 0.7)',
      textInverse: '#1a1a1a',
      textInverseMuted: '#2d2d2d',
      icon: '#ffd700',
      backgroundPage: '#fafafa',
      backgroundSurface: '#ffffff',
      backgroundMuted: '#fafafa',
      backgroundContrast: '#f5e7a1',
      backgroundContrastMuted: '#f9e076',
      border: '#e5d5a1',
      borderStrong: '#d9c48e',
      accent: '#d4af37',
      accentStrong: '#ffd700',
      accentSoft: 'rgba(212, 175, 55, 0.12)',
      focus: '#d4af37',
      success: '#15803d',
      warning: '#b45309',
      danger: '#dc2626',
      info: '#1d4ed8',
      selected: '#d4af37',
      selectedBg: 'rgba(212, 175, 55, 0.15)'
    },
    typography: {
      body: 'Inter, sans-serif',
      heading: '"Cormorant Garamond", serif',
      accent: '"Lucy Said Ok Personal Use Italic", "Cormorant Garamond", serif'
    },
    components: {
      buttonPrimary: 'btn-primary theme-button-primary',
      buttonOutline: 'btn-outline theme-button-outline',
      link: 'theme-link',
      input: 'theme-input',
      navItem: 'theme-nav-item',
      surface: 'theme-bg-surface theme-border',
      surfaceMuted: 'theme-bg-muted theme-border'
    },
    utilities: {
      textPrimary: 'theme-text-primary',
      textSecondary: 'theme-text-secondary',
      textMuted: 'theme-text-muted',
      textInverse: 'theme-text-inverse',
      bgPage: 'theme-bg-page',
      bgSurface: 'theme-bg-surface',
      bgMuted: 'theme-bg-muted',
      bgContrast: 'theme-bg-contrast',
      border: 'theme-border',
      borderStrong: 'theme-border-strong',
      selected: 'theme-selected',
      selectedBg: 'theme-selected-bg',
      textDanger: 'text-red-600'
    },
    cssVars: {
      'font-body': 'Inter, sans-serif',
      'font-heading': '"Cormorant Garamond", serif',
      'font-accent': '"Lucy Said Ok Personal Use Italic", "Cormorant Garamond", serif',
      'color-text-primary': '#d4af37',
      'color-text-secondary': '#ffd700',
      'color-text-muted': 'rgba(212, 175, 55, 0.7)',
      'color-text-inverse': '#1a1a1a',
      'color-text-inverse-muted': '#2d2d2d',
      'color-icon': '#ffd700',
      'color-bg-page': '#fafafa',
      'color-bg-surface': '#ffffff',
      'color-bg-muted': '#fafafa',
      'color-bg-contrast': '#f5e7a1',
      'color-bg-contrast-muted': '#f9e076',
      'color-border': '#e5d5a1',
      'color-border-strong': '#d9c48e',
      'color-accent': '#d4af37',
      'color-accent-strong': '#ffd700',
      'color-accent-soft': 'rgba(212, 175, 55, 0.12)',
      'color-focus': '#d4af37',
      'color-success': '#15803d',
      'color-warning': '#b45309',
      'color-danger': '#dc2626',
      'color-info': '#1d4ed8',
      'color-success-bg': 'rgba(21, 128, 61, 0.12)',
      'color-warning-bg': 'rgba(180, 83, 9, 0.12)',
      'color-danger-bg': 'rgba(220, 38, 38, 0.12)',
      'color-info-bg': 'rgba(29, 78, 216, 0.12)',
      'color-selected': '#d4af37',
      'color-selected-bg': 'rgba(212, 175, 55, 0.15)',
      'color-button-bg': '#d4af37',
      'color-button-text': '#1a1a1a',
      'color-button-border': '#d4af37',
      'color-button-outline-text': '#d4af37',
      'color-button-outline-bg': 'transparent',
      'color-button-outline-border': '#d4af37',
      'color-input-bg': '#ffffff',
      'color-input-border': '#e5d5a1',
      'color-input-text': '#d4af37',
      'color-input-placeholder': 'rgba(212, 175, 55, 0.6)',
      'color-nav-bg': '#ffffff',
      'color-nav-border': '#e5d5a1',
      'color-logo-gold': '#d4af37',
      'color-logo-highlight': '#ffd700',
      'color-logo-glow': 'rgba(212, 175, 55, 0.75)',
      'color-logo-glow-strong': 'rgba(255, 215, 0, 0.9)',
      'color-logo-glow-soft': 'rgba(212, 175, 55, 0.45)'
    }
  }
};

export const defaultThemeKey = 'dark';

export const resolveThemeKey = (key) => (themes[key] ? key : defaultThemeKey);

export const getNextThemeKey = (currentKey) => {
  const currentIndex = themeOrder.indexOf(currentKey);
  const nextIndex = currentIndex === -1 ? 0 : (currentIndex + 1) % themeOrder.length;
  return themeOrder[nextIndex];
};
